### ISSUE TITLE
헤더 수정

### ISSUE THREAD

**Issue by Sung-jin** [yapp-project/team02_frontend#22]
### 개요

* 제플린에 올라와 있는 헤더 형태로 레이아웃 및 기능 구현

### 레이아웃

* [x] 고정헤더 (로그인 전/후)
* [x] 검색창

### 기능

* [x] 로그인 전/후 처리
* [x] 검색창 생성 처리

**Comment by AnGwangHo** [comment]
로그인 전/후 처리, 검색창 생성 해놨어 퇴근하고 pr할께
style이랑 검색창 열었을때 메인 추천 칵테일이랑 겹쳐서 나타나는 것만 잡으면 될듯

**Comment by Sung-jin** [comment]
그래여??? 그.. pr 날리기 전인지는 잘 모르겠는데 일단 메인뷰단에 있는 헤더부분 거기에 어느정도 반영되어있는데 그거랑 제가 좀 손볼려고 했거든요

그러면 pr 하시면 제가 받고 합칠께요

**Comment by AnGwangHo** [comment]
일단 지금 내가 하나 판 브랜치에 로그아웃까진 푸쉬 해놨음.
내가 pr하면 너가 css쪽만 잡아주면 될 것 같아

- 로그인 전/후 버튼 변화 css
- 검색창 오픈 시 콤보(태그/재료 기반)들 css 깨지는문제 ->이거는 너가 합치면 내가 잡을게(신경 ㄴㄴ)
- 검색 결과 창 나타났을 때 Main페이지의 칵테일 이미지와 겹쳐서 표현되는 문제
   >z-index로 잡아볼려 했는데 안 먹었음(css 다 건들려고 했다가 gg)
   >검색창, 결과창 자체를 header div에 삽입하여 header에 종속되게 구현할 예정

※etc
- 서버 통신할때 get 방식으로 body에 data 담아서 통신이 가능하니?(안되면 이거 서버쪽보고 query로 바꾸라고 해야함)

**Comment by Sung-jin** [comment]
릴리즈 거기 브랜치말고 #19 이 브랜치에 제일 마지막에 있는 내용들이 그렇다는거죠??

**Comment by AnGwangHo** [comment]
yes, 그 브랜치 맞아

**Comment by Sung-jin** [comment]
음.. 지금 브랜치에 올라와있는게 지금까지 작업 최신본인가여? 더 있다는건가여? pr 날린다는 의미가 어떤건가여

**Comment by AnGwangHo** [comment]
지금 #19브랜치에 올라가 있는게 로그아웃 까지 반영된거고 추가로 작업한거 더 있는데 아직 푸쉬안해서 퇴근하고 pr날린다는 거임.

**Comment by Sung-jin** [comment]
넵넵 그러면 추가 pr 받고 그거 풀 받아서 확인해볼께요

**Comment by Sung-jin** [comment]
음.... 합쳐서 봤는데 제가 어디부분을 하면 되는걸까요?? 이벤트가 어떻게 해야 동작되는지랑 어떤거를 제가 손대야 될지 명확하지 않아서 우선은 이번주 세션때 만나서 이야기하는거로 해요 그 외에 것들 할게요

**Comment by AnGwangHo** [comment]
> 음.... 합쳐서 봤는데 제가 어디부분을 하면 되는걸까요?? 이벤트가 어떻게 해야 동작되는지랑 어떤거를 제가 손대야 될지 명확하지 않아서 우선은 이번주 세션때 만나서 이야기하는거로 해요 그 외에 것들 할게요

자세한건 이번주에 만나서 얘기하고 일단은 합친 상태로 두자.
레시피 쪽 먼저하고 있으렴.
